// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://riqfafiivzpotfjqfscd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpcWZhZmlpdnpwb3RmanFmc2NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjExMDcsImV4cCI6MjA3MTUzNzEwN30.TGxCyriLKuvI1r8_MJPtGiEctXOCrXkyk0ez-LRWjto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});